export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const SEARCH_GIFS = 'SEARCH_GIFS';
export const SEARCH_GIFS_SUCCESS = 'SEARCH_GIFS_SUCCESS';
export const SEARCH_GIFS_ERROR = 'SEARCH_GIFS_ERROR';